name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
        working-directory: ./tslint
      - name: Lint
        uses: saby/github-actions/tslint@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
          config: 'tslint/tslint.json'
      - name: Build
        run: npm run build
        working-directory: ./tslint
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
